# Generated by hand for TanPit drain flags

import django.db.models.deletion
import pits.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pits", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="DrainFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("date", models.DateField(default=pits.models._today)),
                ("state", models.CharField(max_length=20)),
                ("inspector", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_by", models.CharField(blank=True, max_length=64)),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drain_flags",
                        to="pits.yard",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(voided_at__isnull=True),
                        fields=("yard", "date"),
                        name="uniq_active_flag_per_yard_day",
                    )
                ],
            },
        ),
    ]
