# Generated by hand for TanPit ditch flags

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="DitchFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_date", models.DateField()),
                ("state", models.CharField(max_length=10)),
                ("inspector", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_by", models.CharField(blank=True, max_length=64)),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ditch_flags",
                        to="pits.yard",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ditchflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(voided_at__isnull=True),
                fields=("yard", "check_date"),
                name="uniq_active_ditch_flag_per_yard_day",
            ),
        ),
    ]
